# Generated by Django 5.2.8 on 2025-12-17 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('vagas', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=100)),
                ('telefone_solicitante', models.CharField(max_length=20)),
                ('visto_passageiro', models.BooleanField(default=True)),
                ('visto_viagem', models.BooleanField(default=False)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('uuid_local', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('token_cancelamento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('carona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='viagens.carona')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
