# Generated by Django 5.2.8 on 2025-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='tipo_valor',
            field=models.CharField(choices=[('dinheiro', 'Valor em dinheiro'), ('combinar', 'A combinar'), ('gratuita', 'Gratuita')], default='combinar', max_length=10),
        ),
        migrations.AddField(
            model_name='carona',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
