# Generated by Django 5.2.8 on 2025-12-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_veiculo_carona_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=10),
        ),
    ]
