# Generated by Django 5.2.8 on 2025-12-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_carona_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10),
        ),
    ]
