# Generated by Django 5.2.8 on 2025-12-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0005_alter_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
