# Generated by Django 5.2.8 on 2025-12-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0006_carona_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='malas',
            field=models.IntegerField(choices=[(0, 'Nenhuma'), (1, '1 mala'), (2, '2 malas'), (3, '3 ou mais malas')], default=0),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
