# Generated by Django 5.2.8 on 2025-12-24 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0007_solicitacao_malas_solicitacao_observacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='visto_passageiro',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='visto_viagem',
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitacao_recebida', 'Solicitação recebida'), ('solicitacao_aceita', 'Solicitação aceita'), ('solicitacao_recusada', 'Solicitação recusada'), ('viagem_cancelada', 'Viagem cancelada'), ('viagem_concluida', 'Viagem concluída')], max_length=40)),
                ('titulo', models.CharField(max_length=120)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('carona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viagens.carona')),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viagens.solicitacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
