# Generated by Django 5.2.8 on 2025-12-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0008_remove_solicitacao_visto_passageiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('solicitacao_recebida', 'Solicitação recebida'), ('solicitacao_aceita', 'Solicitação aceita'), ('solicitacao_recusada', 'Solicitação recusada'), ('viagem_aceita', 'Viagem confirmada'), ('viagem_cancelada', 'Viagem cancelada'), ('viagem_concluida', 'Viagem concluída')], max_length=40),
        ),
    ]
