# Generated by Django 5.2.8 on 2025-12-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0010_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('solicitacao_recebida', 'Solicitação recebida'), ('solicitacao_recusada', 'Solicitação recusada'), ('viagem_aceita', 'Viagem confirmada'), ('viagem_atualizada', 'Viagem atualizada'), ('viagem_cancelada', 'Viagem cancelada'), ('viagem_concluida', 'Viagem concluída')], max_length=40),
        ),
    ]
