# Generated by Django 5.2.8 on 2025-12-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0011_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='viagem_atualizada',
            field=models.BooleanField(default=False),
        ),
    ]
