# Generated by Django 5.2.8 on 2025-12-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0012_solicitacao_viagem_atualizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
