# Generated by Django 5.2.8 on 2025-12-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0013_solicitacao_data_edicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_edicao',
        ),
        migrations.AddField(
            model_name='carona',
            name='data_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carona',
            name='viagem_atualizada',
            field=models.BooleanField(default=False),
        ),
    ]
