# Generated by Django 5.2.8 on 2025-12-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0014_remove_solicitacao_data_edicao_carona_data_edicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
