# Generated by Django 5.2.8 on 2026-01-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0015_solicitacao_data_edicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('solicitacao_recebida', 'Solicitação recebida'), ('solicitacao_recusada', 'Solicitação recusada'), ('viagem_aceita', 'Viagem confirmada'), ('viagem_atualizada', 'Viagem atualizada'), ('viagem_cancelada', 'Viagem cancelada'), ('viagem_concluida', 'Viagem concluída'), ('passageiro_cancelou', 'Passageiro cancelou')], max_length=40),
        ),
    ]
