# Generated by Django 6.0.2 on 2026-02-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0016_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='descricao_item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='foto_encomenda',
            field=models.ImageField(blank=True, null=True, upload_to='encomendas/fotos/'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('carona', 'Carona'), ('encomenda', 'Encomenda')], default='carona', max_length=20),
        ),
    ]
