# Generated by Django 5.2.8 on 2026-03-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0019_solicitacao_endereco_destino_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='ObservaÃ§Ãµes'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('concluida', 'ConcluÃ\xadda'), ('cancelada', 'Cancelada')], default='ativa', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('solicitacao_recebida', 'SolicitaÃ§Ã£o recebida'), ('solicitacao_recusada', 'SolicitaÃ§Ã£o recusada'), ('viagem_aceita', 'Viagem confirmada'), ('viagem_atualizada', 'Viagem atualizada'), ('viagem_cancelada', 'Viagem cancelada'), ('viagem_concluida', 'Viagem concluÃ\xadda'), ('passageiro_cancelou', 'Passageiro cancelou')], max_length=40),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('van', 'Van'), ('onibus', 'Onibus / Micro-onibus')], max_length=20),
        ),
    ]
