# Generated by Django 5.2.8 on 2026-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0022_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=10),
        ),
    ]
