# Generated by Django 5.2.8 on 2026-09-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0023_alter_carona_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='encomendas_abertas',
            field=models.BooleanField(default=True),
        ),
    ]
