from django.urls import path
from . import views

urlpatterns = [
    path('', views.lista_caronas, name='lista_caronas'),
    path('nova/', views.criar_carona, name='criar_carona'),
    path("minhas-caronas/", views.minhas_caronas_view, name="minhas_caronas"),
    path('caronas/<int:carona_id>/editar/', views.editar_carona, name='editar_carona'),
    path('caronas/<int:carona_id>/excluir/', views.excluir_carona, name='excluir_carona'),
    path("caronas/<int:carona_id>/solicitar/", views.solicitar_vaga, name="solicitar_vaga"),
    path("caronas/<int:carona_id>/encomenda/", views.solicitar_encomenda, name="solicitar_encomenda"),
    path("solicitacoes/", views.gerenciar_solicitacoes, name="gerenciar_solicitacoes"),
    path("encomendas/", views.minhas_encomendas, name="minhas_encomendas"),
    path("minhas-encomendas/", views.minhas_encomendas_passageiro, name="minhas_encomendas_passageiro"),
    path("minhas-encomendas/carona/<int:carona_id>/", views.minhas_encomendas_carona_passageiro, name="minhas_encomendas_carona_passageiro"),
    path("caronas/<int:carona_id>/encomendas/", views.encomendas_carona, name="encomendas_carona"),
    path("solicitacao/<int:solicitacao_id>/aceitar/", views.aceitar_solicitacao, name="aceitar_solicitacao"),
    path("solicitacao/<int:solicitacao_id>/recusar/", views.recusar_solicitacao, name="recusar_solicitacao"),
    path('cancelar/<int:id>/', views.cancelar_solicitacao, name='cancelar_solicitacao'),
    path('minhas-solicitacoes/', views.minhas_solicitacoes, name='minhas_solicitacoes'),
    path('minhas-viagens/', views.minhas_viagens, name='minhas_viagens'),
    path("api/status-solicitacoes/", views.api_status_solicitacoes, name="api_status_solicitacoes"),
    path("cancelar-solicitacao-publica/<int:id>/",views.cancelar_solicitacao_publica, name="cancelar_solicitacao_publica"),
    path("meus-veiculos/", views.meus_veiculos, name="meus_veiculos"),
    path("veiculos/criar/", views.criar_veiculo, name="criar_veiculo"),
    path("veiculos/<int:veiculo_id>/editar/", views.editar_veiculo, name="editar_veiculo"),
    path("veiculos/<int:veiculo_id>/excluir/", views.excluir_veiculo, name="excluir_veiculo"),
    path('historico/', views.historico_viagens, name='historico_viagens'), 
    path('carona/<int:carona_id>/concluir/', views.concluir_carona, name='concluir_carona'),
    path("api/estado-caronas/", views.api_estado_caronas, name="api_estado_caronas"),
    path("solicitacao/<int:pk>/remover/", views.remover_passageiro, name="remover_passageiro"),
    path("solicitacao/<int:pk>/cancelar-encomenda-motorista/", views.cancelar_encomenda_motorista, name="cancelar_encomenda_motorista"),
    path("notificacoes/marcar-lidas/", views.marcar_notificacoes_como_lidas, name="marcar_notificacoes_como_lidas"),
]
